# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info_tea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 13, 43, 2, 253961, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
