# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_milight', '0012_lightautomation_turn_display_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightgroup',
            name='on_until_task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
