# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_milight', '0013_lightgroup_on_until_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LightAutomation',
        ),
        migrations.DeleteModel(
            name='LightGroup',
        ),
    ]
