# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_air_quality', '0005_auto_20150326_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airdatapoint',
            name='timepoint',
        ),
        migrations.DeleteModel(
            name='AirDataPoint',
        ),
        migrations.DeleteModel(
            name='AirTimePoint',
        ),
    ]
