# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_timers', '0006_auto_20160224_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='alarm_0s_task',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='alarm_300s_task',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='alarm_30s_task',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='alarm_600s_task',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='alarm_60s_task',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='alarm_ending_task',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='alarm_until_dismissed_task',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
